services:
  store-database:
    container_name: store-database
    build:
      context: ./database
    volumes:
      - mysqldata:/data/db
    env_file:
      - ./env/mysql.env
    ports:
      - 3307:3307
    networks:
      - store-app

  products-api:
    container_name: products-api
    build:
      context: ./products-api
    volumes:
      - ./products-api/src:/app/src
    ports:
      - 8080:8080
    env_file:
      - ./env/products-api.env
    depends_on:
      - store-database
      - rabbitmq
    networks:
      - store-app

  notifications-api:
    container_name: notifications-api
    build:
      context: ./notifications-api
    ports:
      - 5000:5000
    networks:
      - store-app

  frontend:
    container_name: store-frontend
    build:
      context: ./store-frontend
    volumes:
      - ./store-frontend/src:/app/src
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
    depends_on:
      - products-api
    networks:
      - store-app

  rabbitmq:
    container_name: rabbit_mq
    build:
      context: ./rabbitmq
    env_file:
      - ./env/rabbitmq.env
    depends_on:
      - notifications-api
    ports:
      - 5672:5672
    networks:
      - store-app

networks:
  store-app:
    driver: bridge

volumes:
  mysqldata:
